### ISSUE TITLE
Amélioration / Nerf

### ISSUE THREAD

**Issue by StevenSa34** [minemakers/shulker-rush#1]
Bonjours, c'est StevenSa#0019
on c'est parler sur discord, 

dans les "probleme" que 'j'avais remarqué c'est la puissance de divers objet, et d'autre qui pourrait etre rajouter qui peuvent etre sympathique donc ;

- La possibilité de limité le nombre d'article maximum par inventaire (1 fiole explosive max par équipe ou 2 arbalète par inventaire)
cela permettrez comme dans les exemple de nerf la possibilité de snowball avec plusieurs arbalète ou spam de fiole explosive.
           - Possibilité de l'imité l'inventaire du joueur
           - Possibilité de limité la possession par équipe

- Trident avec l'enchantement loyauté ou loyalty en englais, cela permettrai de rajouter une arme plutôt sympathique
- possibilité de crée c'est propre carte 
- rajouter une interface graphique ou commande permettant de crée cette dite maps (je sais pas si c'est possible)

- Possibilité de custom entièrement le shop de façon simplifiée ( ce qui es vendu )
- possibilité de crée des pnj nous même  sur les maps ( comme sur la maps steampunk par exemple )

dans le theme de chose permettant trop facilement de snowball peut etre faire des patch pour :
Fiole explosive (trop facile de tuer quelqu'un)
arbalète comme dit précédemment (le faite de stack beaucoup d'arbellete permet de limite spam mitraillette)
feu d'artifice trop abuser le limiter donc avec un chrono ou le limité par inventaire mais un chrono serais vraiment pas mal un espece de cooldown

et sinon sa serait tout, si vous avez des questions hesitez pas a me mp discord StevenSa#0019

**Comment by aksiome** [comment]
- Limiter le nombre d'item malheureusement est un peu trop compliqué et surtout ça risque de faire très cheap (Il faut gérer non pas que l'achat mais aussi le pickup d'un item au sol ou dans un coffre).
- Pour le trident c'est une chouette idée.
- Tout ce qui est interface de création de maps / shops custom c'était pas vraiment le but de la maj. L'idée était seulement de pouvoir modifier la config facilement directement depuis les fichiers. Ce qui est maintenant le cas à savoir changer les prix, les items permanents et la vitesse des générateurs.
- La fiole vient déjà d'être nerf à voir ce que ça donne maintenant...
- L'idée du cooldown pour le feu d'artifice est intéressante, peut être un peu compliqué à mettre en place mais je pense qu'il y a moyen de trouver quelque chose qui marche bien !
