### ISSUE TITLE
Merchants sell nameless items

### ISSUE THREAD

**Issue by shurik204** [minemakers/shulker-rush#11]
![Screenshot_20220828_211231](https://user-images.githubusercontent.com/43310372/187088613-3820f853-fd5e-4f68-b085-651879f3c47d.png)

And here's something rather weird about this:

https://user-images.githubusercontent.com/43310372/187088674-376e3a9a-5bfa-4795-998f-43f762120e77.mp4

**Comment by aksiome** [comment]
Weird I can't reproduce this issue at all! Using the prefab or starting the game works for me just fine both in english and russian!

**Comment by shurik204** [comment]
![Screenshot_20221011-180447](https://user-images.githubusercontent.com/43310372/195129563-769f1c29-d543-4ca9-b768-3ee078378ca6.png)

**Comment by aksiome** [comment]
Run into this issue when i was updating makers wars ! Now I'm pretty sure it happens when the server run the function . A quick fix would be to execute the function as an arbitrary player.
