### ISSUE TITLE
Ender chest broken in 1.19

### ISSUE THREAD

**Issue by shurik204** [minemakers/shulker-rush#7]
Ender chest system works fine, but gets confused if you put something into the last slot.

https://user-images.githubusercontent.com/43310372/187063584-03a62292-70bd-4d4d-bb3e-39122d0425bd.mp4

**Comment by aksiome** [comment]
Hum weird. I love this system as much as I hate it x). At first it seemed like a brilliant idea but what a nightmare to maintain! I'll try to see what I can do about this one.
